"""
Django settings for project_academia project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_#y%+gfz!9&cdkqvay9z_08w_&#hh)5dq(vo32o9ob37b=n%#o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'academia',
    'django_celery_beat',
    'sslserver',
]


CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'academia.middleware.SessionTimeoutMiddleware',
    'academia.middleware.DeviceMiddleware',
]

ROOT_URLCONF = 'project_academia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'academia' / 'templates' / 'academia'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'academia.context_processors.user_info',
                'academia.context_processors.current_path',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_academia.wsgi.application'


# Email Settings

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hlaminnaing105@gmail.com'
EMAIL_HOST_PASSWORD = 'vohn unvr ffmb qhgh'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'MIIT Academia <noreply@example.com>'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Academia',
        'USER': 'root',
        'PASSWORD': 'Hla@013',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'DB_Academia',
#         'USER': '2017-CSE-013',
#         'PASSWORD': '2017-MIIT-cse-013',
#         'HOST': '10.10.100.85',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'academia.auth_backends.MIITUserBackend',
]

AUTH_USER_MODEL = 'academia.MIITUsers'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_HTTPONLY = True

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True

# Additional settings for SSL
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# CSRF_TRUSTED_ORIGINS = ['http://172.16.217.21:8080']





SESSION_COOKIE_AGE = 1800  # Default 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

ROLE_SESSION_TIMEOUT = {
    'R01': 600,  # 10 minutes
    'R07': 1200,  # 20 minutes
    'R09': 1200,  # 20 minutes
    'R06': 1200,  # 20 minutes
}

RECAPTCHA_PUBLIC_KEY = '6LfCkPQpAAAAAFz9o4DsWB73lI06lnOSgWAImzMW'
RECAPTCHA_PRIVATE_KEY = '6LfCkPQpAAAAAO4RpY0FkZa6KthGZDb_q51_1Prb'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
